###########################################
#
#        BungeeHubSystem v1.1.1
#          by Maximilian1021
#
###########################################


#Messages
Prefix: '§aLobby §7|'

Move-to-Lobby: '§bDu wurdest auf die §6§lLobby §bgesendet!'
Move-to-LobbyFB: '§bDu wurdest auf die §6§lFallback Lobby §bgesendet! §7- §bDie §6Haupt Lobby §bist §cnicht §berreichbar'
No-Player: '§cError §7| §bDu musst ein Spieler sein um dies zu tun!'
No-Lobby-Online: '§cError §7| §bEs ist keine Lobby online. Wenn du möchtest, kannst du das Team kontaktieren.'

#Gib hier die Daten für den Haupt-Lobby Server an
#Der Haupt-Lobby Name sollte genau so heißen wie in der BungeeConfig angeben. (Beachtung von groß und klein schreibung)

Haupt-Lobby: Lobby
Adress-Hauptlobby: localhost
Port-Hauptlobby: 25561

#Gib hier die Daten für den Fallback Server an
#Der Fallback-Lobby Name sollte genau so heißen in der BungeeConfig angeben. (Beachtung von Groß und klein schreibung)

Fallback-Lobby: LobbyFallback
Adress-Fallback: localhost
Port-Fallback: 25562


###########################################
#
#    Du hast Fragen oder ein Problem?
#      Kontaktiere mich Discord
#         Maximilian1021#2888
#
###########################################